//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_MDK_01_session_one
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int Order_Status_ID { get; set; }
        public string Order_Status { get; set; }
    }
}
